-- Bé Đua Xe — bảng thành tích. Chạy toàn bộ file này trong Supabase > SQL Editor.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  nickname text not null,
  score integer not null default 0,
  level integer not null default 1,
  coins integer not null default 0,
  created_at timestamptz not null default now(),

  constraint nickname_length   check (char_length(nickname) between 2 and 15),
  constraint score_range       check (score >= 0 and score <= 1000000),
  constraint level_valid       check (level between 1 and 100),
  constraint coins_range       check (coins >= 0 and coins <= 100000)
);

create index if not exists leaderboard_score_idx
  on public.leaderboard (score desc);

alter table public.leaderboard enable row level security;

-- Ai cũng được xem bảng thành tích.
drop policy if exists "Public can read leaderboard" on public.leaderboard;
create policy "Public can read leaderboard"
  on public.leaderboard
  for select
  using (true);

-- ⚠️ CHỈ DÙNG CHO MVP: cho phép gửi điểm ẩn danh (có kiểm tra giá trị hợp lệ).
-- Client không thể tự bảo vệ điểm số hoàn toàn. Nếu bảng có giá trị thi đấu thật,
-- hãy xoá policy này và chuyển sang Edge Function (kiểm tra điểm phía server,
-- giới hạn tần suất, đăng nhập ẩn danh).
drop policy if exists "MVP anonymous insert" on public.leaderboard;
create policy "MVP anonymous insert"
  on public.leaderboard
  for insert
  to anon
  with check (
    char_length(nickname) between 2 and 15
    and score between 0 and 1000000
    and level between 1 and 10
    and coins between 0 and 100000
  );

-- Không cấp quyền update / delete cho anon => người chơi không sửa hay xoá được điểm.
